### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by ugintl** [mhmamun6316/inventory_management_system#2]
It would be very helpful if you can share the installation steps.

**Comment by mhmamun6316** [comment]
First of all download the project then go the directory and open terminal . Then follow these commands
composer update
cp .env.example .env
then create a database same name as in env file
php artisan key:generate
php artisan migrate
php artisan serve

**Comment by ugintl** [comment]
Thanks. Is the `php artisan serve` command only for local or production as well?

**Comment by mhmamun6316** [comment]
its only for local server
